"""Create all tables properly

Revision ID: 21738d47ae82
Revises: 12532e93966d
Create Date: 2026-02-09 01:30:43.516161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21738d47ae82'
down_revision: Union[str, None] = '12532e93966d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alliances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXTINCT', name='alliancestatus'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('founded_month', sa.Integer(), nullable=True),
    sa.Column('founded_day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('SHOOTING', 'STABBING', 'BEATING', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_year', sa.Integer(), nullable=True),
    sa.Column('date_month', sa.Integer(), nullable=True),
    sa.Column('date_day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('NEWS_ARTICLE', 'COURT_DOCUMENT', 'SOCIAL_MEDIA', 'VIDEO', 'WITNESS', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_year', sa.Integer(), nullable=True),
    sa.Column('date_month', sa.Integer(), nullable=True),
    sa.Column('date_day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alliance_sources',
    sa.Column('alliance_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('alliance_id', 'source_id')
    )
    op.create_table('incident_sources',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'source_id')
    )
    op.create_table('sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('primary_name', sa.String(), nullable=False),
    sa.Column('names', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXTINCT', name='setstatus'), nullable=False),
    sa.Column('territory', sa.String(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('alliance_id', sa.String(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('founded_month', sa.Integer(), nullable=True),
    sa.Column('founded_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('nicknames', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ALIVE_FREE', 'ALIVE_LOCKED_UP', 'DEAD', 'UNKNOWN', name='memberstatus'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('social_media', sa.JSON(), nullable=True),
    sa.Column('affiliation_type', sa.Enum('SET', 'ALLIANCE', 'CIVILIAN', 'UNKNOWN', name='affiliationtype'), nullable=False),
    sa.Column('set_id', sa.String(), nullable=True),
    sa.Column('alliance_id', sa.String(), nullable=True),
    sa.Column('dob_year', sa.Integer(), nullable=True),
    sa.Column('dob_month', sa.Integer(), nullable=True),
    sa.Column('dob_day', sa.Integer(), nullable=True),
    sa.Column('dod_year', sa.Integer(), nullable=True),
    sa.Column('dod_month', sa.Integer(), nullable=True),
    sa.Column('dod_day', sa.Integer(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('release_month', sa.Integer(), nullable=True),
    sa.Column('release_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set_allies',
    sa.Column('set_a_id', sa.String(), nullable=False),
    sa.Column('set_b_id', sa.String(), nullable=False),
    sa.Column('since_year', sa.Integer(), nullable=True),
    sa.Column('since_month', sa.Integer(), nullable=True),
    sa.Column('since_day', sa.Integer(), nullable=True),
    sa.CheckConstraint('set_a_id < set_b_id', name='set_allies_order_check'),
    sa.ForeignKeyConstraint(['set_a_id'], ['sets.id'], ),
    sa.ForeignKeyConstraint(['set_b_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('set_a_id', 'set_b_id')
    )
    op.create_table('set_enemies',
    sa.Column('set_a_id', sa.String(), nullable=False),
    sa.Column('set_b_id', sa.String(), nullable=False),
    sa.Column('since_year', sa.Integer(), nullable=True),
    sa.Column('since_month', sa.Integer(), nullable=True),
    sa.Column('since_day', sa.Integer(), nullable=True),
    sa.CheckConstraint('set_a_id < set_b_id', name='set_enemies_order_check'),
    sa.ForeignKeyConstraint(['set_a_id'], ['sets.id'], ),
    sa.ForeignKeyConstraint(['set_b_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('set_a_id', 'set_b_id')
    )
    op.create_table('set_sources',
    sa.Column('set_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('set_id', 'source_id')
    )
    op.create_table('incident_participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('PERPETRATOR', 'ACCOMPLICE', 'VICTIM', name='participantrole'), nullable=False),
    sa.Column('outcome', sa.Enum('UNHARMED', 'WOUNDED', 'KILLED', name='victimoutcome'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_sources',
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_sources')
    op.drop_table('incident_participants')
    op.drop_table('set_sources')
    op.drop_table('set_enemies')
    op.drop_table('set_allies')
    op.drop_table('members')
    op.drop_table('sets')
    op.drop_table('incident_sources')
    op.drop_table('alliance_sources')
    op.drop_table('sources')
    op.drop_table('incidents')
    op.drop_table('alliances')
    # ### end Alembic commands ###
