"""initial schema

Revision ID: b1380d6a914d
Revises: 
Create Date: 2026-04-19 03:27:11.027652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = 'b1380d6a914d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('global_role', sa.Enum('ADMIN', 'USER', name='globalrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='auditaction'), nullable=False),
    sa.Column('diff_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('universe',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universe_name'), 'universe', ['name'], unique=False)
    op.create_index(op.f('ix_universe_slug'), 'universe', ['slug'], unique=True)
    op.create_table('alliance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('universe_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXTINCT', 'DORMANT', name='alliancestatus'), nullable=False),
    sa.Column('founded_at', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alliance_name'), 'alliance', ['name'], unique=False)
    op.create_index(op.f('ix_alliance_universe_id'), 'alliance', ['universe_id'], unique=False)
    op.create_table('municipality',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('universe_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['municipality.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipality_universe_id'), 'municipality', ['universe_id'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('universe_id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publication', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accessed_at', sa.Date(), nullable=True),
    sa.Column('reliability', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNVERIFIED', name='sourcereliability'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('archive_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_universe_id'), 'source', ['universe_id'], unique=False)
    op.create_table('user_universe_access',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('universe_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EDITOR', 'VIEWER', name='universerole'), nullable=False),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'universe_id')
    )
    op.create_table('alliance_municipality',
    sa.Column('alliance_id', sa.Uuid(), nullable=False),
    sa.Column('municipality_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliance.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ),
    sa.PrimaryKeyConstraint('alliance_id', 'municipality_id')
    )
    op.create_table('incident',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('universe_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('SHOOTING', 'MURDER', name='incidenttype'), nullable=False),
    sa.Column('date', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sortable_date', sa.DateTime(), nullable=True),
    sa.Column('municipality_id', sa.Uuid(), nullable=True),
    sa.Column('location_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('narrative', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_sortable_date'), 'incident', ['sortable_date'], unique=False)
    op.create_index(op.f('ix_incident_universe_id'), 'incident', ['universe_id'], unique=False)
    op.create_table('sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('universe_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXTINCT', name='setstatus'), nullable=False),
    sa.Column('alliance_id', sa.Uuid(), nullable=True),
    sa.Column('founder_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliance.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['founder_id'], ['member.id'], name='fk_sets_founder_id', use_alter=True),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sets_name'), 'sets', ['name'], unique=False)
    op.create_index(op.f('ix_sets_universe_id'), 'sets', ['universe_id'], unique=False)
    op.create_table('alliance_set',
    sa.Column('alliance_id', sa.Uuid(), nullable=False),
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliance.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('alliance_id', 'set_id')
    )
    op.create_table('incident_source',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'source_id')
    )
    op.create_table('member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('universe_id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nickname_unknown', sa.Boolean(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('biography', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('set_id', sa.Uuid(), nullable=True),
    sa.Column('alliance_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('FREE', 'LOCKED', 'DEAD', 'UNKNOWN', 'ESCAPEE', 'ABSCONDER', name='memberstatus'), nullable=False),
    sa.Column('dob', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_of_death', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('release_date', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('family', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('social_media', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliance.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_alliance_id'), 'member', ['alliance_id'], unique=False)
    op.create_index(op.f('ix_member_legal_name'), 'member', ['legal_name'], unique=False)
    op.create_index(op.f('ix_member_nickname'), 'member', ['nickname'], unique=False)
    op.create_index(op.f('ix_member_set_id'), 'member', ['set_id'], unique=False)
    op.create_index(op.f('ix_member_universe_id'), 'member', ['universe_id'], unique=False)
    op.create_table('set_municipality',
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.Column('municipality_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('set_id', 'municipality_id')
    )
    op.create_table('set_relationships',
    sa.Column('set_a_id', sa.Uuid(), nullable=False),
    sa.Column('set_b_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('FRIEND', 'ENEMY', name='setrelationshiptype'), nullable=False),
    sa.CheckConstraint('set_a_id < set_b_id', name='ck_set_relationship_ordering'),
    sa.ForeignKeyConstraint(['set_a_id'], ['sets.id'], ),
    sa.ForeignKeyConstraint(['set_b_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('set_a_id', 'set_b_id'),
    sa.UniqueConstraint('set_a_id', 'set_b_id', name='uq_set_relationship_pair')
    )
    op.create_table('incident_participant',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('SHOOTER', 'ASSISTED', 'BYSTANDER', 'VICTIM', name='participantrole'), nullable=False),
    sa.Column('outcome', sa.Enum('KILLED', 'INJURED', 'UNHARMED', 'UNKNOWN', name='participantoutcome'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'member_id')
    )
    op.create_table('member_source',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'source_id')
    )
    # Bilateral relationship trigger — second layer after the CHECK constraint.
    # asyncpg requires separate execute() per statement.
    op.execute("""
        CREATE OR REPLACE FUNCTION enforce_set_relationship_ordering()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.set_a_id >= NEW.set_b_id THEN
                RAISE EXCEPTION
                    'set_a_id must be strictly less than set_b_id (got % >= %)',
                    NEW.set_a_id, NEW.set_b_id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER trg_set_relationship_ordering
        BEFORE INSERT OR UPDATE ON set_relationships
        FOR EACH ROW EXECUTE FUNCTION enforce_set_relationship_ordering()
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_set_relationship_ordering ON set_relationships")
    op.execute("DROP FUNCTION IF EXISTS enforce_set_relationship_ordering")
    op.drop_table('member_source')
    op.drop_table('incident_participant')
    op.drop_table('set_relationships')
    op.drop_table('set_municipality')
    op.drop_index(op.f('ix_member_universe_id'), table_name='member')
    op.drop_index(op.f('ix_member_set_id'), table_name='member')
    op.drop_index(op.f('ix_member_nickname'), table_name='member')
    op.drop_index(op.f('ix_member_legal_name'), table_name='member')
    op.drop_index(op.f('ix_member_alliance_id'), table_name='member')
    op.drop_table('member')
    op.drop_table('incident_source')
    op.drop_table('alliance_set')
    op.drop_index(op.f('ix_sets_universe_id'), table_name='sets')
    op.drop_index(op.f('ix_sets_name'), table_name='sets')
    op.drop_table('sets')
    op.drop_index(op.f('ix_incident_universe_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_sortable_date'), table_name='incident')
    op.drop_table('incident')
    op.drop_table('alliance_municipality')
    op.drop_table('user_universe_access')
    op.drop_index(op.f('ix_source_universe_id'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_municipality_universe_id'), table_name='municipality')
    op.drop_table('municipality')
    op.drop_index(op.f('ix_alliance_universe_id'), table_name='alliance')
    op.drop_index(op.f('ix_alliance_name'), table_name='alliance')
    op.drop_table('alliance')
    op.drop_index(op.f('ix_universe_slug'), table_name='universe')
    op.drop_index(op.f('ix_universe_name'), table_name='universe')
    op.drop_table('universe')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
