/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUniversesRouteImport } from './routes/_app.universes'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppUniverseRouteImport } from './routes/_app.$universe'
import { Route as AppUniverseIndexRouteImport } from './routes/_app.$universe.index'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminGangsRouteImport } from './routes/_app.admin.gangs'
import { Route as AppUniverseTimelineRouteImport } from './routes/_app.$universe.timeline'
import { Route as AppUniverseMapRouteImport } from './routes/_app.$universe.map'
import { Route as AppUniverseCalendarRouteImport } from './routes/_app.$universe.calendar'
import { Route as AppUniverseSourcesIndexRouteImport } from './routes/_app.$universe.sources.index'
import { Route as AppUniverseSetsIndexRouteImport } from './routes/_app.$universe.sets.index'
import { Route as AppUniverseResearchIndexRouteImport } from './routes/_app.$universe.research.index'
import { Route as AppUniverseMunicipalitiesIndexRouteImport } from './routes/_app.$universe.municipalities.index'
import { Route as AppUniverseMembersIndexRouteImport } from './routes/_app.$universe.members.index'
import { Route as AppUniverseIncidentsIndexRouteImport } from './routes/_app.$universe.incidents.index'
import { Route as AppUniverseGangsIndexRouteImport } from './routes/_app.$universe.gangs.index'
import { Route as AppUniverseAlliancesIndexRouteImport } from './routes/_app.$universe.alliances.index'
import { Route as AppUniverseSourcesIdRouteImport } from './routes/_app.$universe.sources.$id'
import { Route as AppUniverseSetsIdRouteImport } from './routes/_app.$universe.sets.$id'
import { Route as AppUniverseResearchIdRouteImport } from './routes/_app.$universe.research.$id'
import { Route as AppUniverseMunicipalitiesMapRouteImport } from './routes/_app.$universe.municipalities.map'
import { Route as AppUniverseMunicipalitiesIdRouteImport } from './routes/_app.$universe.municipalities.$id'
import { Route as AppUniverseMembersIdRouteImport } from './routes/_app.$universe.members.$id'
import { Route as AppUniverseIncidentsIdRouteImport } from './routes/_app.$universe.incidents.$id'
import { Route as AppUniverseGangsIdRouteImport } from './routes/_app.$universe.gangs.$id'
import { Route as AppUniverseAlliancesIdRouteImport } from './routes/_app.$universe.alliances.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUniversesRoute = AppUniversesRouteImport.update({
  id: '/universes',
  path: '/universes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppUniverseRoute = AppUniverseRouteImport.update({
  id: '/$universe',
  path: '/$universe',
  getParentRoute: () => AppRoute,
} as any)
const AppUniverseIndexRoute = AppUniverseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUniverseRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminGangsRoute = AppAdminGangsRouteImport.update({
  id: '/admin/gangs',
  path: '/admin/gangs',
  getParentRoute: () => AppRoute,
} as any)
const AppUniverseTimelineRoute = AppUniverseTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppUniverseRoute,
} as any)
const AppUniverseMapRoute = AppUniverseMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppUniverseRoute,
} as any).lazy(() =>
  import('./routes/_app.$universe.map.lazy').then((d) => d.Route),
)
const AppUniverseCalendarRoute = AppUniverseCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppUniverseRoute,
} as any)
const AppUniverseSourcesIndexRoute = AppUniverseSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => AppUniverseRoute,
} as any).lazy(() =>
  import('./routes/_app.$universe.sources.index.lazy').then((d) => d.Route),
)
const AppUniverseSetsIndexRoute = AppUniverseSetsIndexRouteImport.update({
  id: '/sets/',
  path: '/sets/',
  getParentRoute: () => AppUniverseRoute,
} as any).lazy(() =>
  import('./routes/_app.$universe.sets.index.lazy').then((d) => d.Route),
)
const AppUniverseResearchIndexRoute =
  AppUniverseResearchIndexRouteImport.update({
    id: '/research/',
    path: '/research/',
    getParentRoute: () => AppUniverseRoute,
  } as any)
const AppUniverseMunicipalitiesIndexRoute =
  AppUniverseMunicipalitiesIndexRouteImport.update({
    id: '/municipalities/',
    path: '/municipalities/',
    getParentRoute: () => AppUniverseRoute,
  } as any).lazy(() =>
    import('./routes/_app.$universe.municipalities.index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppUniverseMembersIndexRoute = AppUniverseMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AppUniverseRoute,
} as any)
const AppUniverseIncidentsIndexRoute =
  AppUniverseIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => AppUniverseRoute,
  } as any)
const AppUniverseGangsIndexRoute = AppUniverseGangsIndexRouteImport.update({
  id: '/gangs/',
  path: '/gangs/',
  getParentRoute: () => AppUniverseRoute,
} as any).lazy(() =>
  import('./routes/_app.$universe.gangs.index.lazy').then((d) => d.Route),
)
const AppUniverseAlliancesIndexRoute =
  AppUniverseAlliancesIndexRouteImport.update({
    id: '/alliances/',
    path: '/alliances/',
    getParentRoute: () => AppUniverseRoute,
  } as any).lazy(() =>
    import('./routes/_app.$universe.alliances.index.lazy').then((d) => d.Route),
  )
const AppUniverseSourcesIdRoute = AppUniverseSourcesIdRouteImport.update({
  id: '/sources/$id',
  path: '/sources/$id',
  getParentRoute: () => AppUniverseRoute,
} as any)
const AppUniverseSetsIdRoute = AppUniverseSetsIdRouteImport.update({
  id: '/sets/$id',
  path: '/sets/$id',
  getParentRoute: () => AppUniverseRoute,
} as any).lazy(() =>
  import('./routes/_app.$universe.sets.$id.lazy').then((d) => d.Route),
)
const AppUniverseResearchIdRoute = AppUniverseResearchIdRouteImport.update({
  id: '/research/$id',
  path: '/research/$id',
  getParentRoute: () => AppUniverseRoute,
} as any)
const AppUniverseMunicipalitiesMapRoute =
  AppUniverseMunicipalitiesMapRouteImport.update({
    id: '/municipalities/map',
    path: '/municipalities/map',
    getParentRoute: () => AppUniverseRoute,
  } as any)
const AppUniverseMunicipalitiesIdRoute =
  AppUniverseMunicipalitiesIdRouteImport.update({
    id: '/municipalities/$id',
    path: '/municipalities/$id',
    getParentRoute: () => AppUniverseRoute,
  } as any)
const AppUniverseMembersIdRoute = AppUniverseMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AppUniverseRoute,
} as any)
const AppUniverseIncidentsIdRoute = AppUniverseIncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => AppUniverseRoute,
} as any).lazy(() =>
  import('./routes/_app.$universe.incidents.$id.lazy').then((d) => d.Route),
)
const AppUniverseGangsIdRoute = AppUniverseGangsIdRouteImport.update({
  id: '/gangs/$id',
  path: '/gangs/$id',
  getParentRoute: () => AppUniverseRoute,
} as any).lazy(() =>
  import('./routes/_app.$universe.gangs.$id.lazy').then((d) => d.Route),
)
const AppUniverseAlliancesIdRoute = AppUniverseAlliancesIdRouteImport.update({
  id: '/alliances/$id',
  path: '/alliances/$id',
  getParentRoute: () => AppUniverseRoute,
} as any).lazy(() =>
  import('./routes/_app.$universe.alliances.$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/$universe': typeof AppUniverseRouteWithChildren
  '/audit': typeof AppAuditRoute
  '/profile': typeof AppProfileRoute
  '/universes': typeof AppUniversesRoute
  '/$universe/calendar': typeof AppUniverseCalendarRoute
  '/$universe/map': typeof AppUniverseMapRoute
  '/$universe/timeline': typeof AppUniverseTimelineRoute
  '/admin/gangs': typeof AppAdminGangsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/$universe/': typeof AppUniverseIndexRoute
  '/$universe/alliances/$id': typeof AppUniverseAlliancesIdRoute
  '/$universe/gangs/$id': typeof AppUniverseGangsIdRoute
  '/$universe/incidents/$id': typeof AppUniverseIncidentsIdRoute
  '/$universe/members/$id': typeof AppUniverseMembersIdRoute
  '/$universe/municipalities/$id': typeof AppUniverseMunicipalitiesIdRoute
  '/$universe/municipalities/map': typeof AppUniverseMunicipalitiesMapRoute
  '/$universe/research/$id': typeof AppUniverseResearchIdRoute
  '/$universe/sets/$id': typeof AppUniverseSetsIdRoute
  '/$universe/sources/$id': typeof AppUniverseSourcesIdRoute
  '/$universe/alliances/': typeof AppUniverseAlliancesIndexRoute
  '/$universe/gangs/': typeof AppUniverseGangsIndexRoute
  '/$universe/incidents/': typeof AppUniverseIncidentsIndexRoute
  '/$universe/members/': typeof AppUniverseMembersIndexRoute
  '/$universe/municipalities/': typeof AppUniverseMunicipalitiesIndexRoute
  '/$universe/research/': typeof AppUniverseResearchIndexRoute
  '/$universe/sets/': typeof AppUniverseSetsIndexRoute
  '/$universe/sources/': typeof AppUniverseSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/profile': typeof AppProfileRoute
  '/universes': typeof AppUniversesRoute
  '/': typeof AppIndexRoute
  '/$universe/calendar': typeof AppUniverseCalendarRoute
  '/$universe/map': typeof AppUniverseMapRoute
  '/$universe/timeline': typeof AppUniverseTimelineRoute
  '/admin/gangs': typeof AppAdminGangsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/$universe': typeof AppUniverseIndexRoute
  '/$universe/alliances/$id': typeof AppUniverseAlliancesIdRoute
  '/$universe/gangs/$id': typeof AppUniverseGangsIdRoute
  '/$universe/incidents/$id': typeof AppUniverseIncidentsIdRoute
  '/$universe/members/$id': typeof AppUniverseMembersIdRoute
  '/$universe/municipalities/$id': typeof AppUniverseMunicipalitiesIdRoute
  '/$universe/municipalities/map': typeof AppUniverseMunicipalitiesMapRoute
  '/$universe/research/$id': typeof AppUniverseResearchIdRoute
  '/$universe/sets/$id': typeof AppUniverseSetsIdRoute
  '/$universe/sources/$id': typeof AppUniverseSourcesIdRoute
  '/$universe/alliances': typeof AppUniverseAlliancesIndexRoute
  '/$universe/gangs': typeof AppUniverseGangsIndexRoute
  '/$universe/incidents': typeof AppUniverseIncidentsIndexRoute
  '/$universe/members': typeof AppUniverseMembersIndexRoute
  '/$universe/municipalities': typeof AppUniverseMunicipalitiesIndexRoute
  '/$universe/research': typeof AppUniverseResearchIndexRoute
  '/$universe/sets': typeof AppUniverseSetsIndexRoute
  '/$universe/sources': typeof AppUniverseSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$universe': typeof AppUniverseRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/universes': typeof AppUniversesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$universe/calendar': typeof AppUniverseCalendarRoute
  '/_app/$universe/map': typeof AppUniverseMapRoute
  '/_app/$universe/timeline': typeof AppUniverseTimelineRoute
  '/_app/admin/gangs': typeof AppAdminGangsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/$universe/': typeof AppUniverseIndexRoute
  '/_app/$universe/alliances/$id': typeof AppUniverseAlliancesIdRoute
  '/_app/$universe/gangs/$id': typeof AppUniverseGangsIdRoute
  '/_app/$universe/incidents/$id': typeof AppUniverseIncidentsIdRoute
  '/_app/$universe/members/$id': typeof AppUniverseMembersIdRoute
  '/_app/$universe/municipalities/$id': typeof AppUniverseMunicipalitiesIdRoute
  '/_app/$universe/municipalities/map': typeof AppUniverseMunicipalitiesMapRoute
  '/_app/$universe/research/$id': typeof AppUniverseResearchIdRoute
  '/_app/$universe/sets/$id': typeof AppUniverseSetsIdRoute
  '/_app/$universe/sources/$id': typeof AppUniverseSourcesIdRoute
  '/_app/$universe/alliances/': typeof AppUniverseAlliancesIndexRoute
  '/_app/$universe/gangs/': typeof AppUniverseGangsIndexRoute
  '/_app/$universe/incidents/': typeof AppUniverseIncidentsIndexRoute
  '/_app/$universe/members/': typeof AppUniverseMembersIndexRoute
  '/_app/$universe/municipalities/': typeof AppUniverseMunicipalitiesIndexRoute
  '/_app/$universe/research/': typeof AppUniverseResearchIndexRoute
  '/_app/$universe/sets/': typeof AppUniverseSetsIndexRoute
  '/_app/$universe/sources/': typeof AppUniverseSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$universe'
    | '/audit'
    | '/profile'
    | '/universes'
    | '/$universe/calendar'
    | '/$universe/map'
    | '/$universe/timeline'
    | '/admin/gangs'
    | '/admin/users'
    | '/$universe/'
    | '/$universe/alliances/$id'
    | '/$universe/gangs/$id'
    | '/$universe/incidents/$id'
    | '/$universe/members/$id'
    | '/$universe/municipalities/$id'
    | '/$universe/municipalities/map'
    | '/$universe/research/$id'
    | '/$universe/sets/$id'
    | '/$universe/sources/$id'
    | '/$universe/alliances/'
    | '/$universe/gangs/'
    | '/$universe/incidents/'
    | '/$universe/members/'
    | '/$universe/municipalities/'
    | '/$universe/research/'
    | '/$universe/sets/'
    | '/$universe/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/profile'
    | '/universes'
    | '/'
    | '/$universe/calendar'
    | '/$universe/map'
    | '/$universe/timeline'
    | '/admin/gangs'
    | '/admin/users'
    | '/$universe'
    | '/$universe/alliances/$id'
    | '/$universe/gangs/$id'
    | '/$universe/incidents/$id'
    | '/$universe/members/$id'
    | '/$universe/municipalities/$id'
    | '/$universe/municipalities/map'
    | '/$universe/research/$id'
    | '/$universe/sets/$id'
    | '/$universe/sources/$id'
    | '/$universe/alliances'
    | '/$universe/gangs'
    | '/$universe/incidents'
    | '/$universe/members'
    | '/$universe/municipalities'
    | '/$universe/research'
    | '/$universe/sets'
    | '/$universe/sources'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$universe'
    | '/_app/audit'
    | '/_app/profile'
    | '/_app/universes'
    | '/_app/'
    | '/_app/$universe/calendar'
    | '/_app/$universe/map'
    | '/_app/$universe/timeline'
    | '/_app/admin/gangs'
    | '/_app/admin/users'
    | '/_app/$universe/'
    | '/_app/$universe/alliances/$id'
    | '/_app/$universe/gangs/$id'
    | '/_app/$universe/incidents/$id'
    | '/_app/$universe/members/$id'
    | '/_app/$universe/municipalities/$id'
    | '/_app/$universe/municipalities/map'
    | '/_app/$universe/research/$id'
    | '/_app/$universe/sets/$id'
    | '/_app/$universe/sources/$id'
    | '/_app/$universe/alliances/'
    | '/_app/$universe/gangs/'
    | '/_app/$universe/incidents/'
    | '/_app/$universe/members/'
    | '/_app/$universe/municipalities/'
    | '/_app/$universe/research/'
    | '/_app/$universe/sets/'
    | '/_app/$universe/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/universes': {
      id: '/_app/universes'
      path: '/universes'
      fullPath: '/universes'
      preLoaderRoute: typeof AppUniversesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$universe': {
      id: '/_app/$universe'
      path: '/$universe'
      fullPath: '/$universe'
      preLoaderRoute: typeof AppUniverseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$universe/': {
      id: '/_app/$universe/'
      path: '/'
      fullPath: '/$universe/'
      preLoaderRoute: typeof AppUniverseIndexRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/gangs': {
      id: '/_app/admin/gangs'
      path: '/admin/gangs'
      fullPath: '/admin/gangs'
      preLoaderRoute: typeof AppAdminGangsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$universe/timeline': {
      id: '/_app/$universe/timeline'
      path: '/timeline'
      fullPath: '/$universe/timeline'
      preLoaderRoute: typeof AppUniverseTimelineRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/map': {
      id: '/_app/$universe/map'
      path: '/map'
      fullPath: '/$universe/map'
      preLoaderRoute: typeof AppUniverseMapRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/calendar': {
      id: '/_app/$universe/calendar'
      path: '/calendar'
      fullPath: '/$universe/calendar'
      preLoaderRoute: typeof AppUniverseCalendarRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/sources/': {
      id: '/_app/$universe/sources/'
      path: '/sources'
      fullPath: '/$universe/sources/'
      preLoaderRoute: typeof AppUniverseSourcesIndexRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/sets/': {
      id: '/_app/$universe/sets/'
      path: '/sets'
      fullPath: '/$universe/sets/'
      preLoaderRoute: typeof AppUniverseSetsIndexRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/research/': {
      id: '/_app/$universe/research/'
      path: '/research'
      fullPath: '/$universe/research/'
      preLoaderRoute: typeof AppUniverseResearchIndexRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/municipalities/': {
      id: '/_app/$universe/municipalities/'
      path: '/municipalities'
      fullPath: '/$universe/municipalities/'
      preLoaderRoute: typeof AppUniverseMunicipalitiesIndexRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/members/': {
      id: '/_app/$universe/members/'
      path: '/members'
      fullPath: '/$universe/members/'
      preLoaderRoute: typeof AppUniverseMembersIndexRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/incidents/': {
      id: '/_app/$universe/incidents/'
      path: '/incidents'
      fullPath: '/$universe/incidents/'
      preLoaderRoute: typeof AppUniverseIncidentsIndexRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/gangs/': {
      id: '/_app/$universe/gangs/'
      path: '/gangs'
      fullPath: '/$universe/gangs/'
      preLoaderRoute: typeof AppUniverseGangsIndexRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/alliances/': {
      id: '/_app/$universe/alliances/'
      path: '/alliances'
      fullPath: '/$universe/alliances/'
      preLoaderRoute: typeof AppUniverseAlliancesIndexRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/sources/$id': {
      id: '/_app/$universe/sources/$id'
      path: '/sources/$id'
      fullPath: '/$universe/sources/$id'
      preLoaderRoute: typeof AppUniverseSourcesIdRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/sets/$id': {
      id: '/_app/$universe/sets/$id'
      path: '/sets/$id'
      fullPath: '/$universe/sets/$id'
      preLoaderRoute: typeof AppUniverseSetsIdRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/research/$id': {
      id: '/_app/$universe/research/$id'
      path: '/research/$id'
      fullPath: '/$universe/research/$id'
      preLoaderRoute: typeof AppUniverseResearchIdRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/municipalities/map': {
      id: '/_app/$universe/municipalities/map'
      path: '/municipalities/map'
      fullPath: '/$universe/municipalities/map'
      preLoaderRoute: typeof AppUniverseMunicipalitiesMapRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/municipalities/$id': {
      id: '/_app/$universe/municipalities/$id'
      path: '/municipalities/$id'
      fullPath: '/$universe/municipalities/$id'
      preLoaderRoute: typeof AppUniverseMunicipalitiesIdRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/members/$id': {
      id: '/_app/$universe/members/$id'
      path: '/members/$id'
      fullPath: '/$universe/members/$id'
      preLoaderRoute: typeof AppUniverseMembersIdRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/incidents/$id': {
      id: '/_app/$universe/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/$universe/incidents/$id'
      preLoaderRoute: typeof AppUniverseIncidentsIdRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/gangs/$id': {
      id: '/_app/$universe/gangs/$id'
      path: '/gangs/$id'
      fullPath: '/$universe/gangs/$id'
      preLoaderRoute: typeof AppUniverseGangsIdRouteImport
      parentRoute: typeof AppUniverseRoute
    }
    '/_app/$universe/alliances/$id': {
      id: '/_app/$universe/alliances/$id'
      path: '/alliances/$id'
      fullPath: '/$universe/alliances/$id'
      preLoaderRoute: typeof AppUniverseAlliancesIdRouteImport
      parentRoute: typeof AppUniverseRoute
    }
  }
}

interface AppUniverseRouteChildren {
  AppUniverseCalendarRoute: typeof AppUniverseCalendarRoute
  AppUniverseMapRoute: typeof AppUniverseMapRoute
  AppUniverseTimelineRoute: typeof AppUniverseTimelineRoute
  AppUniverseIndexRoute: typeof AppUniverseIndexRoute
  AppUniverseAlliancesIdRoute: typeof AppUniverseAlliancesIdRoute
  AppUniverseGangsIdRoute: typeof AppUniverseGangsIdRoute
  AppUniverseIncidentsIdRoute: typeof AppUniverseIncidentsIdRoute
  AppUniverseMembersIdRoute: typeof AppUniverseMembersIdRoute
  AppUniverseMunicipalitiesIdRoute: typeof AppUniverseMunicipalitiesIdRoute
  AppUniverseMunicipalitiesMapRoute: typeof AppUniverseMunicipalitiesMapRoute
  AppUniverseResearchIdRoute: typeof AppUniverseResearchIdRoute
  AppUniverseSetsIdRoute: typeof AppUniverseSetsIdRoute
  AppUniverseSourcesIdRoute: typeof AppUniverseSourcesIdRoute
  AppUniverseAlliancesIndexRoute: typeof AppUniverseAlliancesIndexRoute
  AppUniverseGangsIndexRoute: typeof AppUniverseGangsIndexRoute
  AppUniverseIncidentsIndexRoute: typeof AppUniverseIncidentsIndexRoute
  AppUniverseMembersIndexRoute: typeof AppUniverseMembersIndexRoute
  AppUniverseMunicipalitiesIndexRoute: typeof AppUniverseMunicipalitiesIndexRoute
  AppUniverseResearchIndexRoute: typeof AppUniverseResearchIndexRoute
  AppUniverseSetsIndexRoute: typeof AppUniverseSetsIndexRoute
  AppUniverseSourcesIndexRoute: typeof AppUniverseSourcesIndexRoute
}

const AppUniverseRouteChildren: AppUniverseRouteChildren = {
  AppUniverseCalendarRoute: AppUniverseCalendarRoute,
  AppUniverseMapRoute: AppUniverseMapRoute,
  AppUniverseTimelineRoute: AppUniverseTimelineRoute,
  AppUniverseIndexRoute: AppUniverseIndexRoute,
  AppUniverseAlliancesIdRoute: AppUniverseAlliancesIdRoute,
  AppUniverseGangsIdRoute: AppUniverseGangsIdRoute,
  AppUniverseIncidentsIdRoute: AppUniverseIncidentsIdRoute,
  AppUniverseMembersIdRoute: AppUniverseMembersIdRoute,
  AppUniverseMunicipalitiesIdRoute: AppUniverseMunicipalitiesIdRoute,
  AppUniverseMunicipalitiesMapRoute: AppUniverseMunicipalitiesMapRoute,
  AppUniverseResearchIdRoute: AppUniverseResearchIdRoute,
  AppUniverseSetsIdRoute: AppUniverseSetsIdRoute,
  AppUniverseSourcesIdRoute: AppUniverseSourcesIdRoute,
  AppUniverseAlliancesIndexRoute: AppUniverseAlliancesIndexRoute,
  AppUniverseGangsIndexRoute: AppUniverseGangsIndexRoute,
  AppUniverseIncidentsIndexRoute: AppUniverseIncidentsIndexRoute,
  AppUniverseMembersIndexRoute: AppUniverseMembersIndexRoute,
  AppUniverseMunicipalitiesIndexRoute: AppUniverseMunicipalitiesIndexRoute,
  AppUniverseResearchIndexRoute: AppUniverseResearchIndexRoute,
  AppUniverseSetsIndexRoute: AppUniverseSetsIndexRoute,
  AppUniverseSourcesIndexRoute: AppUniverseSourcesIndexRoute,
}

const AppUniverseRouteWithChildren = AppUniverseRoute._addFileChildren(
  AppUniverseRouteChildren,
)

interface AppRouteChildren {
  AppUniverseRoute: typeof AppUniverseRouteWithChildren
  AppAuditRoute: typeof AppAuditRoute
  AppProfileRoute: typeof AppProfileRoute
  AppUniversesRoute: typeof AppUniversesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminGangsRoute: typeof AppAdminGangsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppUniverseRoute: AppUniverseRouteWithChildren,
  AppAuditRoute: AppAuditRoute,
  AppProfileRoute: AppProfileRoute,
  AppUniversesRoute: AppUniversesRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminGangsRoute: AppAdminGangsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
