/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUniversesRouteImport } from './routes/_app.universes'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppSourcesIndexRouteImport } from './routes/_app.sources.index'
import { Route as AppSetsIndexRouteImport } from './routes/_app.sets.index'
import { Route as AppResearchIndexRouteImport } from './routes/_app.research.index'
import { Route as AppMunicipalitiesIndexRouteImport } from './routes/_app.municipalities.index'
import { Route as AppMembersIndexRouteImport } from './routes/_app.members.index'
import { Route as AppIncidentsIndexRouteImport } from './routes/_app.incidents.index'
import { Route as AppAlliancesIndexRouteImport } from './routes/_app.alliances.index'
import { Route as AppSourcesIdRouteImport } from './routes/_app.sources.$id'
import { Route as AppSetsIdRouteImport } from './routes/_app.sets.$id'
import { Route as AppResearchIdRouteImport } from './routes/_app.research.$id'
import { Route as AppMunicipalitiesIdRouteImport } from './routes/_app.municipalities.$id'
import { Route as AppMembersIdRouteImport } from './routes/_app.members.$id'
import { Route as AppIncidentsIdRouteImport } from './routes/_app.incidents.$id'
import { Route as AppAlliancesIdRouteImport } from './routes/_app.alliances.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUniversesRoute = AppUniversesRouteImport.update({
  id: '/universes',
  path: '/universes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesIndexRoute = AppSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => AppRoute,
} as any)
const AppSetsIndexRoute = AppSetsIndexRouteImport.update({
  id: '/sets/',
  path: '/sets/',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchIndexRoute = AppResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => AppRoute,
} as any)
const AppMunicipalitiesIndexRoute = AppMunicipalitiesIndexRouteImport.update({
  id: '/municipalities/',
  path: '/municipalities/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIndexRoute = AppIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlliancesIndexRoute = AppAlliancesIndexRouteImport.update({
  id: '/alliances/',
  path: '/alliances/',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesIdRoute = AppSourcesIdRouteImport.update({
  id: '/sources/$id',
  path: '/sources/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSetsIdRoute = AppSetsIdRouteImport.update({
  id: '/sets/$id',
  path: '/sets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchIdRoute = AppResearchIdRouteImport.update({
  id: '/research/$id',
  path: '/research/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMunicipalitiesIdRoute = AppMunicipalitiesIdRouteImport.update({
  id: '/municipalities/$id',
  path: '/municipalities/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersIdRoute = AppMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIdRoute = AppIncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAlliancesIdRoute = AppAlliancesIdRouteImport.update({
  id: '/alliances/$id',
  path: '/alliances/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/calendar': typeof AppCalendarRoute
  '/map': typeof AppMapRoute
  '/profile': typeof AppProfileRoute
  '/universes': typeof AppUniversesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/alliances/$id': typeof AppAlliancesIdRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/members/$id': typeof AppMembersIdRoute
  '/municipalities/$id': typeof AppMunicipalitiesIdRoute
  '/research/$id': typeof AppResearchIdRoute
  '/sets/$id': typeof AppSetsIdRoute
  '/sources/$id': typeof AppSourcesIdRoute
  '/alliances/': typeof AppAlliancesIndexRoute
  '/incidents/': typeof AppIncidentsIndexRoute
  '/members/': typeof AppMembersIndexRoute
  '/municipalities/': typeof AppMunicipalitiesIndexRoute
  '/research/': typeof AppResearchIndexRoute
  '/sets/': typeof AppSetsIndexRoute
  '/sources/': typeof AppSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/calendar': typeof AppCalendarRoute
  '/map': typeof AppMapRoute
  '/profile': typeof AppProfileRoute
  '/universes': typeof AppUniversesRoute
  '/': typeof AppIndexRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/alliances/$id': typeof AppAlliancesIdRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/members/$id': typeof AppMembersIdRoute
  '/municipalities/$id': typeof AppMunicipalitiesIdRoute
  '/research/$id': typeof AppResearchIdRoute
  '/sets/$id': typeof AppSetsIdRoute
  '/sources/$id': typeof AppSourcesIdRoute
  '/alliances': typeof AppAlliancesIndexRoute
  '/incidents': typeof AppIncidentsIndexRoute
  '/members': typeof AppMembersIndexRoute
  '/municipalities': typeof AppMunicipalitiesIndexRoute
  '/research': typeof AppResearchIndexRoute
  '/sets': typeof AppSetsIndexRoute
  '/sources': typeof AppSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/map': typeof AppMapRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/universes': typeof AppUniversesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/alliances/$id': typeof AppAlliancesIdRoute
  '/_app/incidents/$id': typeof AppIncidentsIdRoute
  '/_app/members/$id': typeof AppMembersIdRoute
  '/_app/municipalities/$id': typeof AppMunicipalitiesIdRoute
  '/_app/research/$id': typeof AppResearchIdRoute
  '/_app/sets/$id': typeof AppSetsIdRoute
  '/_app/sources/$id': typeof AppSourcesIdRoute
  '/_app/alliances/': typeof AppAlliancesIndexRoute
  '/_app/incidents/': typeof AppIncidentsIndexRoute
  '/_app/members/': typeof AppMembersIndexRoute
  '/_app/municipalities/': typeof AppMunicipalitiesIndexRoute
  '/_app/research/': typeof AppResearchIndexRoute
  '/_app/sets/': typeof AppSetsIndexRoute
  '/_app/sources/': typeof AppSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/calendar'
    | '/map'
    | '/profile'
    | '/universes'
    | '/admin/users'
    | '/alliances/$id'
    | '/incidents/$id'
    | '/members/$id'
    | '/municipalities/$id'
    | '/research/$id'
    | '/sets/$id'
    | '/sources/$id'
    | '/alliances/'
    | '/incidents/'
    | '/members/'
    | '/municipalities/'
    | '/research/'
    | '/sets/'
    | '/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/calendar'
    | '/map'
    | '/profile'
    | '/universes'
    | '/'
    | '/admin/users'
    | '/alliances/$id'
    | '/incidents/$id'
    | '/members/$id'
    | '/municipalities/$id'
    | '/research/$id'
    | '/sets/$id'
    | '/sources/$id'
    | '/alliances'
    | '/incidents'
    | '/members'
    | '/municipalities'
    | '/research'
    | '/sets'
    | '/sources'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/calendar'
    | '/_app/map'
    | '/_app/profile'
    | '/_app/universes'
    | '/_app/'
    | '/_app/admin/users'
    | '/_app/alliances/$id'
    | '/_app/incidents/$id'
    | '/_app/members/$id'
    | '/_app/municipalities/$id'
    | '/_app/research/$id'
    | '/_app/sets/$id'
    | '/_app/sources/$id'
    | '/_app/alliances/'
    | '/_app/incidents/'
    | '/_app/members/'
    | '/_app/municipalities/'
    | '/_app/research/'
    | '/_app/sets/'
    | '/_app/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/universes': {
      id: '/_app/universes'
      path: '/universes'
      fullPath: '/universes'
      preLoaderRoute: typeof AppUniversesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/': {
      id: '/_app/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof AppSourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sets/': {
      id: '/_app/sets/'
      path: '/sets'
      fullPath: '/sets/'
      preLoaderRoute: typeof AppSetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/research/': {
      id: '/_app/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof AppResearchIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/municipalities/': {
      id: '/_app/municipalities/'
      path: '/municipalities'
      fullPath: '/municipalities/'
      preLoaderRoute: typeof AppMunicipalitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/': {
      id: '/_app/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/': {
      id: '/_app/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AppIncidentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alliances/': {
      id: '/_app/alliances/'
      path: '/alliances'
      fullPath: '/alliances/'
      preLoaderRoute: typeof AppAlliancesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/$id': {
      id: '/_app/sources/$id'
      path: '/sources/$id'
      fullPath: '/sources/$id'
      preLoaderRoute: typeof AppSourcesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sets/$id': {
      id: '/_app/sets/$id'
      path: '/sets/$id'
      fullPath: '/sets/$id'
      preLoaderRoute: typeof AppSetsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/research/$id': {
      id: '/_app/research/$id'
      path: '/research/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof AppResearchIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/municipalities/$id': {
      id: '/_app/municipalities/$id'
      path: '/municipalities/$id'
      fullPath: '/municipalities/$id'
      preLoaderRoute: typeof AppMunicipalitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/$id': {
      id: '/_app/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof AppMembersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/$id': {
      id: '/_app/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AppIncidentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alliances/$id': {
      id: '/_app/alliances/$id'
      path: '/alliances/$id'
      fullPath: '/alliances/$id'
      preLoaderRoute: typeof AppAlliancesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppMapRoute: typeof AppMapRoute
  AppProfileRoute: typeof AppProfileRoute
  AppUniversesRoute: typeof AppUniversesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAlliancesIdRoute: typeof AppAlliancesIdRoute
  AppIncidentsIdRoute: typeof AppIncidentsIdRoute
  AppMembersIdRoute: typeof AppMembersIdRoute
  AppMunicipalitiesIdRoute: typeof AppMunicipalitiesIdRoute
  AppResearchIdRoute: typeof AppResearchIdRoute
  AppSetsIdRoute: typeof AppSetsIdRoute
  AppSourcesIdRoute: typeof AppSourcesIdRoute
  AppAlliancesIndexRoute: typeof AppAlliancesIndexRoute
  AppIncidentsIndexRoute: typeof AppIncidentsIndexRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
  AppMunicipalitiesIndexRoute: typeof AppMunicipalitiesIndexRoute
  AppResearchIndexRoute: typeof AppResearchIndexRoute
  AppSetsIndexRoute: typeof AppSetsIndexRoute
  AppSourcesIndexRoute: typeof AppSourcesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppMapRoute: AppMapRoute,
  AppProfileRoute: AppProfileRoute,
  AppUniversesRoute: AppUniversesRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAlliancesIdRoute: AppAlliancesIdRoute,
  AppIncidentsIdRoute: AppIncidentsIdRoute,
  AppMembersIdRoute: AppMembersIdRoute,
  AppMunicipalitiesIdRoute: AppMunicipalitiesIdRoute,
  AppResearchIdRoute: AppResearchIdRoute,
  AppSetsIdRoute: AppSetsIdRoute,
  AppSourcesIdRoute: AppSourcesIdRoute,
  AppAlliancesIndexRoute: AppAlliancesIndexRoute,
  AppIncidentsIndexRoute: AppIncidentsIndexRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
  AppMunicipalitiesIndexRoute: AppMunicipalitiesIndexRoute,
  AppResearchIndexRoute: AppResearchIndexRoute,
  AppSetsIndexRoute: AppSetsIndexRoute,
  AppSourcesIndexRoute: AppSourcesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
